spring:
  application:
    name: accounting-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${KEYCLOAK_URL:http://localhost:9595}/auth/realms/warehouse_realm
  datasource:
    url: jdbc:postgresql://postgres:5432/accounting
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
#  boot:
#    admin:
#      client:
#        url: http://localhost:9889
management:
  endpoints:
    web:
      base-path: /actuator-${spring.application.name}
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    env:
      enabled: true
    info:
      enabled: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
server:
  port: 8011



