spring:
  application:
    name: gateway-service
#  boot:
#    admin:
#      client:
#        url: http://localhost:9889
  cloud:
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
      routes:
        - id: accounting-service
          uri: lb://accounting-service/api/transaction
          predicates:
            Path=/api/transaction/**
          filters:
            TokenRelay=
        - id: finance-service
          uri: lb://finance-service/invoice
          predicates:
            Path=/invoice/**
          filters:
            TokenRelay=
        - id: finance-service2
          uri: lb://finance-service/waybill-status
          predicates:
            Path=/waybill-status/**
          filters:
            TokenRelay=
        - id: product-service
          uri: http://localhost:8013/api/v1/products
          predicates:
            Path=/api/v1/products/**
          filters:
            TokenRelay=
        - id : warehouse-service
          uri: lb://warehouse-service/api/v1/suppliers
          predicates:
            Path=/api/v1/suppliers/**
          filters:
            TokenRelay=
        - id: warehouse-service2
          uri: lb://warehouse-service/api/v1/waybills
          predicates:
            Path=/api/v1/waybills/**
          filters:
            TokenRelay=
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: my-provider
            client-id: warehouse_client
            client-secret: UYDuZirNZExLK9ab2LVZtFYtrV86jiJG
            authorization-grant-type: authorization_code
            redirect-uri: "http://gateway:9090/login/oauth2/code/{registrationId}"
            scope: openid, warehouse.read
        provider:
          my-provider:
            issuer-uri: http://keycloak:8080/auth/realms/warehouse_realm
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
#http://localhost:9595/auth/realms/warehouse_realm/:
#  well-known/openid-configuration:

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
server:
  port: 9090
