
server:
  port: 8013
spring:
#  security:
#    actuator:
#      enabled: false
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${KEYCLOAK_URL:http://localhost:9595}/auth/realms/warehouse_realm
  data:
    mongodb:
      database: product
      host: mongo
      password: admin
      port: 27017
      uri: mongodb://admin:admin@localhost:27017/?authSource=admin
      username: admin
  application:
    name: product-service

#  boot:
#    admin:
#      client:
#        instance:
#        url: http://192.168.1.113:9889
management:
  security:
    enabled: false
  endpoints:
    web:
      base-path: /actuator-${spring.application.name}
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    env:
      enabled: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
