spring:
  application:
    name: stock-service
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${KEYCLOAK_URL:http://keycloak:9595}/auth/realms/warehouse_realm
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC
  datasource:
    url: jdbc:mysql://mysql:3306/stock
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
#  boot:
#    admin:
#      client:
#        url: http://localhost:9889
management:
  endpoints:
    web:
      base-path: /actuator-${spring.application.name}
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    env:
      enabled: true


eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
server:
  port: 8014
