spring:
  application:
    name: stock-service
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: ${KEYCLOAK_URL:http://keycloak:9595}/auth/realms/warehouse_realm
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true
        use_sql_comments: true
  datasource:
    url: jdbc:mysql://mysql:3306/stock?useSSL=false&serverTimezone=UTC?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      auto-offset-reset: earliest
      bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
#  boot:
#    admin:
#      client:
#        url: http://localhost:9889
management:
  endpoints:
    web:
      base-path: /actuator-${spring.application.name}
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      enabled: true
    env:
      enabled: true
server:
  port: 8014
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
kafka:
  host: kafka:9092
  topics:
    waybill-record:
      topic: warehouse-service.waybill-record.0
      consumerGroup: ${spring.application.name}-waybill-record-consumer
      replicationFactor: 1
      retentionInMs: 604800000