
server:
    port: 8015
spring:
    application:
        name: warehouse-service
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://postgres:5432/warehouse
        username: postgres
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
    kafka:
      producer:
        bootstrap-servers: kafka:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#    security:
#        oauth2:
#            resourceserver:
#                jwt:
#                    issuer-uri: ${KEYCLOAK_URL:http://localhost:9595}/auth/realms/warehouse_realm

#    boot:
#        admin:
#            client:
#                url: http://localhost:9889
management:
    endpoints:
        web:
            base-path: /actuator-${spring.application.name}
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always
        info:
            enabled: true
        env:
            enabled: true
eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true
kafka:
  host: kafka:9092
  topics:
    waybill-invoice:
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000
      topicName: ${spring.application.name}.waybill-invoice.0
    waybill-record:
      partitionCount: 1
      replicationFactor: 1
      retentionInMs: 604800000
      topicName: ${spring.application.name}.waybill-record.0
